// Regenerates the site mark everywhere it appears: the masthead component and
// the favicon. The OG card reads the same geometry directly.
//
// The mark is ন over দ — the initials of নমিত দেব, stacked.
//
// Set side by side, the two letters' matras (headstrokes) join and they spell
// নদ, a word. Stacking is the fix, and it is the script's own: breaking the
// matra is a documented Bengali typographic device, and vertical setting is
// precisely what it enables. The two headstrokes then read as parallel rails,
// which is what gives the mark its structure — no separator bar required.
//
// Outlines rather than live text, because the favicon and the OG card have no
// webfont available and all three must be identical. Geometry extracted from
// Anek Bangla at weight 700.
//
// Run `npm run mark` after editing scripts/mark-geometry.json.
import { readFile, writeFile } from 'node:fs/promises';

const g = JSON.parse(await readFile(new URL('./mark-geometry.json', import.meta.url)));

const letters = (fill) =>
  `<g transform="translate(${g.tx},${g.Y1}) scale(1,-1)" fill="${fill}">` +
  `<path d="${g.na}"/>` +
  `<g transform="translate(0,${-g.lead})"><path d="${g.da}"/></g></g>`;

await writeFile(
  new URL('../src/components/Mark.astro', import.meta.url),
  `---
// The site mark: ন over দ, the initials of নমিত দেব.
//
// Stacked rather than set side by side, where their matras would join into the
// word নদ. Monochrome by design: colour on this site belongs to the projects.
//
// Generated by scripts/make-mark.mjs — edit that, not this.
---

<svg class="monogram" viewBox="0 0 ${g.W} ${g.H}" role="img" aria-label="Namit Deb">
  ${letters('currentColor')}
</svg>
`);

// The favicon sits on browser chrome that may be light or dark and cannot see
// the page's theme, so it carries its own media query.
const s = 54 / g.H;
await writeFile(
  new URL('../public/favicon.svg', import.meta.url),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <g transform="translate(${((64 - g.W * s) / 2).toFixed(2)},5) scale(${s.toFixed(5)})">
    ${letters('currentColor')}
  </g>
  <style>
    svg { color: #16161a; }
    @media (prefers-color-scheme: dark) { svg { color: #f2f0ec; } }
  </style>
</svg>
`);

console.log('wrote src/components/Mark.astro and public/favicon.svg');
